<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kopilka.Shared\Kopilka.Shared.csproj" />
    <ProjectReference Include="..\Kopilka.BusinessLogic\Kopilka.BusinessLogic.csproj" />
    <ProjectReference Include="..\Kopilka.DataAccess\Kopilka.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
  </ItemGroup>

  <!-- This ItemGroup is necessary to correctly compile XAML pages in subdirectories in SDK-style WPF projects. -->
  <!-- It ensures that types like 'ChartsPage' are found by the compiler, resolving potential build errors. -->
  <ItemGroup>
    <Page Update="**\*.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
