<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Kopilka.Shared\Kopilka.Shared.csproj" />
    <ProjectReference Include="..\Kopilka.BusinessLogic\Kopilka.BusinessLogic.csproj" />
    <ProjectReference Include="..\Kopilka.DataAccess\Kopilka.DataAccess.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
  </ItemGroup>

</Project>
